version: "3.6"
services:
  frontend:
    container_name: igskolkovo-frontend
    image: index.docker.io/aleksioprime/igskolkovo-frontend
    depends_on:
      - backend
    volumes:
      - ./app/nginx:etc/nginx/conf.d
    ports:
      - "80:80"
  backend:
    container_name: igskolkovo-backend
    image: index.docker.io/aleksioprime/igskolkovo-backend
    command: bash -c "gunicorn django_cache.wsgi --bind 0.0.0.0:8000"
    environment:
      - POSTGRES_DB=igskolkovo
      - POSTGRES_USER=igadmin
      - POSTGRES_PASSWORD=Pox{@K
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=igadmin
      - POSTGRES_PASSWORD=Pox{@K
      - POSTGRES_DB=igskolkovo
    networks:
      - local_net
    ports:
      - "5433:5432"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
