version: "3"
services:
  app:
    container_name: igskolkovo-frontend
    image: index.docker.io/aleksioprime/igskolkovo-frontend
    env_file:
      - .env.front
    networks:
      - local_net
    depends_on:
      - api
      - db
    ports:
      -"8080:8080"
  api:
    container_name: igskolkovo-backend
    image: index.docker.io/aleksioprime/igskolkovo-backend
    env_file:
      - .env.back
      - .env.db
    networks:
      - local_net
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=igadmin
      - POSTGRES_PASSWORD=Pox{@K
      - POSTGRES_DB=igskolkovo
    networks:
      - local_net
    ports:
      - "5432:5432"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
networks:
  local_net:
    driver: bridge
