version: "3"
services:
  app:
    container_name: igskolkovo-frontend
    image: index.docker.io/aleksioprime/igskolkovo-frontend
    networks:
      - local_net
    depends_on:
      - api
      - db
    ports:
      - "8080:8080"
  api:
    container_name: igskolkovo-backend
    image: index.docker.io/aleksioprime/igskolkovo-backend
    command: python3 manage.py runserver localhost:8000
    environment:
      - POSTGRES_DB=igskolkovo
      - POSTGRES_USER=igadmin
      - POSTGRES_PASSWORD=Pox{@K
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - local_net
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=igadmin
      - POSTGRES_PASSWORD=Pox{@K
      - POSTGRES_DB=igskolkovo
    networks:
      - local_net
    ports:
      - "5433:5432"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
    
networks:
  local_net:
    driver: bridge

volumes:
  postgres_data:
