# Generated by Django 3.2.13 on 2022-10-04 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0001_initial'),
        ('member', '0002_auto_20221004_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_card',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='ProfileTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль учителя',
                'verbose_name_plural': 'Профили учителей',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='ProfileStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='assess.classgroup', verbose_name='Класс')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
                'ordering': ['group', 'user'],
            },
        ),
    ]
