# Generated by Django 3.2.13 on 2022-10-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20221004_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleuser',
            options={'ordering': ['name'], 'verbose_name': 'Роль пользователей', 'verbose_name_plural': 'Роли пользователей'},
        ),
    ]
