# Generated by Django 3.2.13 on 2022-10-05 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0002_alter_classgroup_study_year'),
        ('curriculum', '0001_initial'),
        ('member', '0004_alter_roleuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestudent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='profileteacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='WorkLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Часы')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='assess.classgroup', verbose_name='Класс')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='curriculum.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='member.profileteacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Рабочая нагрузка',
                'verbose_name_plural': 'Рабочие нагрузки',
                'ordering': ['teacher'],
            },
        ),
    ]
