# Generated by Django 3.2.13 on 2022-11-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileteacher',
            name='short_name',
            field=models.CharField(max_length=32, null=True, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('O', 'Не указан')], default='O', max_length=1, verbose_name='Пол'),
        ),
    ]
