# Generated by Django 3.2.13 on 2022-11-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20221104_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestudent',
            name='short_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='profileteacher',
            name='short_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Учитель'),
        ),
    ]
