# Generated by Django 3.2.13 on 2022-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20221104_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileteacher',
            name='department',
        ),
        migrations.AddField(
            model_name='profileteacher',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='teacher', to='member.Department', verbose_name='Отдел'),
        ),
    ]
