# Generated by Django 3.2.13 on 2022-11-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20221109_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileteacher',
            old_name='department',
            new_name='departments',
        ),
    ]
