# Generated by Django 3.2.13 on 2023-01-23 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_rename_department_profileteacher_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileteacher',
            name='departments',
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='profileteacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
