# Generated by Django 3.2.13 on 2023-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20230123_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('O', 'Не указан')], default='O', max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
