# Generated by Django 3.2.13 on 2023-01-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleuser',
            name='codename',
            field=models.CharField(default='test', max_length=16, verbose_name='Кодовое имя'),
            preserve_default=False,
        ),
    ]
