# Generated by Django 3.2.13 on 2022-10-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assess', '0002_alter_classgroup_study_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во часов')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'ordering': ['subject', 'class_year'],
            },
        ),
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_rus', models.PositiveIntegerField(verbose_name='Год обучения в РФ')),
                ('year_ib', models.CharField(blank=True, max_length=12, null=True, verbose_name='Год обучения в IB')),
                ('program', models.CharField(choices=[('PYP', 'Primary Years Programme'), ('MYP', 'Middle Years Programme'), ('DP', 'Diploma Programme'), ('FGOS', 'ФГОС')], default='FGOS', max_length=4)),
            ],
            options={
                'verbose_name': 'Год обучения',
                'verbose_name_plural': 'Года обучения',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroupIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=128, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на рус. языке')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='subjectgroup_pic', verbose_name='Картинка')),
                ('program', models.CharField(choices=[('PYP', 'Primary Years Programme'), ('MYP', 'Middle Years Programme'), ('DP', 'Diploma Programme'), ('FGOS', 'ФГОС')], default='FGOS', max_length=4)),
            ],
            options={
                'verbose_name': 'Предметная группа',
                'verbose_name_plural': 'Предметные группы',
                'ordering': ['program', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=32, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=32, null=True, verbose_name='Название на рус. языке')),
                ('id_dnevnik', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID системы Дневник.РУ')),
                ('class_year', models.ManyToManyField(blank=True, related_name='subject', through='curriculum.AcademicPlan', to='curriculum.ClassYear')),
                ('group_ib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='curriculum.subjectgroupib', verbose_name='Предметная группа в IB')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['group_ib', 'name_eng'],
            },
        ),
        migrations.AddField(
            model_name='academicplan',
            name='class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='academicplan',
            name='study_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='assess.studyyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='academicplan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='curriculum.subject', verbose_name='Предмет'),
        ),
    ]
