# Generated by Django 3.2.13 on 2022-10-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_year',
        ),
    ]
