# Generated by Django 3.2.18 on 2023-06-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20230603_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classyear',
            name='program',
            field=models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), (None, 'No program')], default=None, max_length=4, null=True, verbose_name='IB-программа'),
        ),
    ]
