# Generated by Django 3.2.13 on 2022-11-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20221104_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatoratl',
            name='group_eng',
        ),
        migrations.RemoveField(
            model_name='indicatoratl',
            name='group_rus',
        ),
    ]
