# Generated by Django 3.2.13 on 2022-11-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20221104_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAreaFGOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=128, verbose_name='Название на рус. языке')),
                ('type_area', models.CharField(choices=[('НОО', 'Начальная школа'), ('ООО', 'Средняя школа'), ('СОО', 'Старшая школа')], default='FGOS', max_length=3)),
            ],
            options={
                'verbose_name': 'Предметная область',
                'verbose_name_plural': 'Предметные области',
                'ordering': ['type_area', 'name_rus'],
            },
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_eng',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Название на англ. языке'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_rus',
            field=models.CharField(max_length=32, verbose_name='Название на рус. языке'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='curriculum.subjectareafgos', verbose_name='Предметная область в РФ'),
        ),
    ]
