# Generated by Django 3.2.18 on 2023-06-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_classyear_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classyear',
            name='program',
        ),
        migrations.AlterField(
            model_name='subjectgroupib',
            name='program',
            field=models.CharField(choices=[('pyp', 'Primary Years Programme'), ('myp', 'Middle Years Programme'), ('dp', 'Diploma Programme'), (None, 'No program')], default=None, max_length=4, null=True),
        ),
    ]
