# Generated by Django 3.2.13 on 2022-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_auto_20221104_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectareafgos',
            name='type_area',
            field=models.CharField(choices=[('НОО', 'Начальная школа'), ('ООО', 'Средняя школа'), ('СОО', 'Старшая школа')], default='ООО', max_length=3),
        ),
    ]
