# Generated by Django 3.2.13 on 2022-11-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_subjectareafgos_type_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGroupFGOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=128, verbose_name='Название на рус. языке')),
                ('type_area', models.CharField(max_length=128, verbose_name='Тип группы')),
                ('level', models.CharField(choices=[('НОО', 'Начальная школа'), ('ООО', 'Средняя школа'), ('СОО', 'Старшая школа')], default='ООО', max_length=3, verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Предметная группа ФГОС',
                'verbose_name_plural': 'Предметные группы ФГОС',
                'ordering': ['level', 'type_area', 'name_rus'],
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_area',
        ),
        migrations.DeleteModel(
            name='SubjectAreaFGOS',
        ),
        migrations.AddField(
            model_name='subject',
            name='group_fgos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='curriculum.subjectgroupfgos', verbose_name='Предметная область в РФ'),
        ),
    ]
