# Generated by Django 3.2.13 on 2022-11-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_auto_20221104_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectgroupfgos',
            options={'ordering': ['level', 'type_group', 'name_rus'], 'verbose_name': 'Предметная группа ФГОС', 'verbose_name_plural': 'Предметные группы ФГОС'},
        ),
        migrations.RemoveField(
            model_name='subjectgroupfgos',
            name='type_area',
        ),
        migrations.AddField(
            model_name='subjectgroupfgos',
            name='type_group',
            field=models.CharField(choices=[('area', 'Предметная область'), ('direction', 'Направление')], default='area', max_length=9, verbose_name='Тип группы'),
        ),
        migrations.AlterField(
            model_name='subjectgroupfgos',
            name='level',
            field=models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа')], default='ooo', max_length=3, verbose_name='Уровень образования'),
        ),
    ]
