# Generated by Django 3.2.13 on 2022-11-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_auto_20221104_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgroupfgos',
            name='level',
            field=models.CharField(choices=[('noo', 'Начальная школа'), ('ooo', 'Средняя школа'), ('soo', 'Старшая школа'), ('dpsoo', 'DP в старшей школе')], default='ooo', max_length=5, verbose_name='Уровень образования'),
        ),
    ]
