# Generated by Django 3.2.13 on 2022-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_subjectgroupfgos_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectgroupib',
            options={'ordering': ['program', 'id'], 'verbose_name': 'Предметная группа IB', 'verbose_name_plural': 'Предметные группы IB'},
        ),
        migrations.AddField(
            model_name='subject',
            name='type_subject',
            field=models.CharField(choices=[('base', 'Основные уроки'), ('extra', 'Внеурочная деятельность')], default='base', max_length=5, verbose_name='Тип предмета'),
        ),
    ]
