# Generated by Django 3.2.13 on 2022-11-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_auto_20221104_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name_eng',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на англ. языке'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_rus',
            field=models.CharField(max_length=128, verbose_name='Название на рус. языке'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_subject',
            field=models.CharField(choices=[('base', 'Обязательная часть'), ('extra', 'Внеурочная деятельность')], default='base', max_length=5, verbose_name='Тип предмета'),
        ),
    ]
