# Generated by Django 3.2.13 on 2022-11-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_auto_20221105_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectDirection',
            new_name='SubjectDirectionRC',
        ),
        migrations.AlterModelOptions(
            name='recommendsubjectkc',
            options={'ordering': ['subject_group', 'key_concept'], 'verbose_name': 'Рекомендуемый предмет KC', 'verbose_name_plural': 'Рекомендуемые предметы KC'},
        ),
        migrations.AlterModelOptions(
            name='subjectdirectionrc',
            options={'ordering': ['subject_group', 'name_eng'], 'verbose_name': 'Предметное направление RC', 'verbose_name_plural': 'Предметные направления RC'},
        ),
    ]
