# Generated by Django 3.2.13 on 2022-11-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_auto_20221105_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, null=True, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('subject_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aim', to='curriculum.subjectgroupib', verbose_name='Предметная группа')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['subject_group', 'name_eng'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfileIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, null=True, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('description_eng', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание на англ. языке')),
                ('description_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание на рус. языке')),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студента',
                'ordering': ['name_eng'],
            },
        ),
        migrations.RenameField(
            model_name='unitplannermyp',
            old_name='concept_understand',
            new_name='conceptual_understanding',
        ),
        migrations.RenameField(
            model_name='unitplannermyp',
            old_name='form_assessment',
            new_name='formative_assessment',
        ),
        migrations.RenameField(
            model_name='unitplannermyp',
            old_name='info_technology',
            new_name='infocom_technology',
        ),
        migrations.RenameField(
            model_name='unitplannermyp',
            old_name='inter_mindedness',
            new_name='international_mindedness',
        ),
        migrations.RenameField(
            model_name='unitplannermyp',
            old_name='sum_assessment_soi',
            new_name='summative_assessment_soi',
        ),
        migrations.RenameField(
            model_name='unitplannermyp',
            old_name='sum_assessment_task',
            new_name='summative_assessment_task',
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='ps_assessment',
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='service_action',
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='academic_integrity',
            field=models.TextField(blank=True, null=True, verbose_name='Академическая честность'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='description_learner_profile',
            field=models.TextField(blank=True, null=True, verbose_name='Описание развития профиля'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='interdisciplinary',
            field=models.BooleanField(default=False, verbose_name='Междисциплинарный юнит'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='peer_self_assessment',
            field=models.TextField(blank=True, null=True, verbose_name='Взаимное и самооценивание'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='service_as_action',
            field=models.TextField(blank=True, null=True, verbose_name='Служение как действие'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='standardization_moderation',
            field=models.TextField(blank=True, null=True, verbose_name='Стандартизация и модерация'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='atl_skills',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.IndicatorATL', verbose_name='Умения ATL'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание (темы, знания и умения)'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='description_atl',
            field=models.TextField(blank=True, null=True, verbose_name='Описание развития умений'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='differentiation',
            field=models.TextField(blank=True, null=True, verbose_name='Дифференцированный подход'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Обратная связь'),
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='learner_profile',
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='learning_experiences',
            field=models.TextField(blank=True, null=True, verbose_name='Учебная деятельность'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.Objective', verbose_name='Цели предметной группы'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='prior_experiences',
            field=models.TextField(blank=True, null=True, verbose_name='Предыдущий опыт обучения'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Умения'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='statement_inquiry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Формулировка исследования'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='student_expectations',
            field=models.TextField(blank=True, null=True, verbose_name='Ожидания студентов'),
        ),
        migrations.CreateModel(
            name='UnitPlannerMYPID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_integration', models.TextField(blank=True, null=True, verbose_name='Формы интеграции')),
                ('purpose_integration', models.TextField(blank=True, null=True, verbose_name='Цель интеграции')),
                ('additional_subjects', models.ManyToManyField(related_name='inter', to='curriculum.Subject', verbose_name='Линии исследования')),
                ('aims', models.ManyToManyField(blank=True, related_name='inter', to='curriculum.Aim', verbose_name='Цели')),
                ('objectives', models.ManyToManyField(blank=True, related_name='inter', to='curriculum.Objective', verbose_name='Образовательные цели')),
                ('related_concepts', models.ManyToManyField(blank=True, related_name='inter', to='curriculum.RelatedConcept', verbose_name='Сопутствующие концепты')),
                ('unitplan_myp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inter', to='curriculum.unitplannermyp', verbose_name='ЮнитПланер MYP')),
            ],
            options={
                'verbose_name': 'ЮнитПланер MYP (МДП)',
                'verbose_name_plural': 'ЮнитПланеры MYP (МДП)',
                'ordering': ['unitplan_myp'],
            },
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='aims',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.Aim', verbose_name='Цели'),
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='learner_profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='unitplan_myp', to='curriculum.LearnerProfileIB', verbose_name='Профиль студента'),
        ),
    ]
