# Generated by Django 3.2.13 on 2022-11-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_auto_20221105_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofileib',
            name='description_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Описание на англ. языке'),
        ),
        migrations.AlterField(
            model_name='learnerprofileib',
            name='description_rus',
            field=models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке'),
        ),
    ]
