# Generated by Django 3.2.13 on 2022-11-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_auto_20221105_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitplannermyp',
            name='hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во часов'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='learner_profile',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.LearnerProfileIB', verbose_name='Профиль студента'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Номер'),
        ),
    ]
