# Generated by Django 3.2.13 on 2022-11-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_auto_20221105_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitplannermyp',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Номер'),
        ),
    ]
