# Generated by Django 3.2.13 on 2022-11-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_alter_unitplannermyp_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitplannermyp',
            options={'ordering': ['class_year', 'subject', 'title'], 'verbose_name': 'ЮнитПланер MYP', 'verbose_name_plural': 'ЮнитПланеры MYP'},
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='number',
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер'),
        ),
    ]
