# Generated by Django 3.2.13 on 2022-11-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_auto_20221105_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitplannermyp',
            old_name='num',
            new_name='number',
        ),
    ]
