# Generated by Django 3.2.13 on 2022-11-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_rename_num_unitplannermyp_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitplannermyp',
            old_name='number',
            new_name='order',
        ),
    ]
