# Generated by Django 3.2.13 on 2022-11-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_rename_number_unitplannermyp_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitplannermyp',
            options={'ordering': ['class_year', 'subject', 'order', 'title'], 'verbose_name': 'ЮнитПланер MYP', 'verbose_name_plural': 'ЮнитПланеры MYP'},
        ),
    ]
