# Generated by Django 3.2.13 on 2022-11-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_rename_department_profileteacher_departments'),
        ('curriculum', '0020_alter_unitplannermyp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='member.department', verbose_name='Учебное подразделение'),
        ),
    ]
