# Generated by Django 3.2.13 on 2022-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_subject_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitplannermyp',
            name='conceptual_understanding',
            field=models.TextField(blank=True, null=True, verbose_name='Концептуальное понимание'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='statement_inquiry',
            field=models.TextField(blank=True, null=True, verbose_name='Формулировка исследования'),
        ),
    ]
