# Generated by Django 3.2.13 on 2023-01-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_rename_department_profileteacher_departments'),
        ('curriculum', '0022_auto_20221114_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InquiryQuestion',
            new_name='InquiryQuestionMYP',
        ),
        migrations.RenameModel(
            old_name='Reflection',
            new_name='ReflectionMYP',
        ),
    ]
