# Generated by Django 3.2.13 on 2023-01-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_auto_20230110_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitplannerdp',
            options={'ordering': ['class_year', 'subject', 'order', 'title'], 'verbose_name': 'ЮнитПланер DP', 'verbose_name_plural': 'ЮнитПланеры DP'},
        ),
        migrations.AddField(
            model_name='unitplannerdp',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
