# Generated by Django 3.2.13 on 2023-01-13 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_auto_20230110_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATLMappingMYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Описание учебных действий')),
            ],
            options={
                'verbose_name': 'Карта навыков ATL в MYP',
                'verbose_name_plural': 'Карты навыков ATL в MYP',
                'ordering': ['planner', 'objective'],
            },
        ),
        migrations.CreateModel(
            name='SkillATL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на рус. языке')),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillATL', to='curriculum.clusteratl', verbose_name='Кластер ATL')),
            ],
            options={
                'verbose_name': 'ATL Навыки',
                'verbose_name_plural': 'ATL Навыки',
                'ordering': ['cluster', 'name_eng'],
            },
        ),
        migrations.RemoveField(
            model_name='subclusteratl',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='atl_skills',
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='description_atl',
        ),
        migrations.DeleteModel(
            name='IndicatorATL',
        ),
        migrations.DeleteModel(
            name='SubClusterATL',
        ),
        migrations.AddField(
            model_name='atlmappingmyp',
            name='atl',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atlmapping', to='curriculum.skillatl', verbose_name='Навыки ATL'),
        ),
        migrations.AddField(
            model_name='atlmappingmyp',
            name='objective',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atlmapping', to='curriculum.objective', verbose_name='Предметная цель'),
        ),
        migrations.AddField(
            model_name='atlmappingmyp',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlmapping', to='curriculum.unitplannermyp', verbose_name='Планнер MYP'),
        ),
    ]
