# Generated by Django 3.2.13 on 2023-01-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_auto_20230113_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillatl',
            name='description_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Описание на англ. языке'),
        ),
        migrations.AddField(
            model_name='skillatl',
            name='description_rus',
            field=models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке'),
        ),
    ]
