# Generated by Django 3.2.13 on 2023-01-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0027_auto_20230113_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitplannermyp',
            old_name='description_learner_profile',
            new_name='description_lp',
        ),
        migrations.AlterField(
            model_name='unitplannermypid',
            name='additional_subjects',
            field=models.ManyToManyField(related_name='inter', to='curriculum.Subject', verbose_name='Дополнительные предметы'),
        ),
    ]
