# Generated by Django 3.2.13 on 2023-01-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_rename_department_profileteacher_departments'),
        ('curriculum', '0028_auto_20230114_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflectionmyp',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='member.profileteacher', verbose_name='Автор поста'),
        ),
    ]
