# Generated by Django 3.2.13 on 2023-01-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0029_alter_reflectionmyp_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='additional_subjects',
        ),
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='unitplannermypid',
            name='related_concepts',
        ),
        migrations.AddField(
            model_name='atlmappingmyp',
            name='strand',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atlmapping', to='curriculum.strand', verbose_name='Предметный стрэнд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='strands',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.Strand', verbose_name='Стренды предметной группы'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='inter', to='curriculum.Criterion', verbose_name='Критерии оценки'),
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='strands',
            field=models.ManyToManyField(blank=True, related_name='inter', to='curriculum.Strand', verbose_name='Образовательные цели'),
        ),
    ]
