# Generated by Django 3.2.13 on 2023-01-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_auto_20230118_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atlmappingmyp',
            options={'ordering': ['planner', 'strand'], 'verbose_name': 'Карта навыков ATL в MYP', 'verbose_name_plural': 'Карты навыков ATL в MYP'},
        ),
        migrations.RemoveField(
            model_name='atlmappingmyp',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='objectives',
        ),
    ]
