# Generated by Django 3.2.13 on 2023-01-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0031_auto_20230118_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitplannermyp',
            options={'ordering': ['class_year', 'order', 'title'], 'verbose_name': 'ЮнитПланер MYP', 'verbose_name_plural': 'ЮнитПланеры MYP'},
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.Subject', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='unitplannermyp',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplan_myp_old', to='curriculum.subject', verbose_name='Учебный предмет'),
        ),
    ]
