# Generated by Django 3.2.13 on 2023-01-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_auto_20230119_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedconcept',
            options={'ordering': ['subdirections__subject_group', 'name_eng'], 'verbose_name': 'Сопутствующий концепт', 'verbose_name_plural': 'Сопутствующие концепты'},
        ),
    ]
