# Generated by Django 3.2.13 on 2023-01-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0033_alter_relatedconcept_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='interdisciplinary',
        ),
    ]
