# Generated by Django 3.2.13 on 2023-01-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0034_remove_unitplannermyp_interdisciplinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitplannermyp',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unitplan_myp', to='curriculum.level', verbose_name='Уровень'),
        ),
    ]
