# Generated by Django 3.2.13 on 2023-01-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0035_unitplannermyp_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='subject',
        ),
    ]
