# Generated by Django 3.2.13 on 2023-01-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0036_remove_unitplannermyp_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='subjects',
        ),
    ]
