# Generated by Django 3.2.13 on 2023-01-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0037_remove_unitplannermyp_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectLevelMYP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_unit', to='curriculum.level', verbose_name='Уровень')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_unit', to='curriculum.subject', verbose_name='Предмет')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_unit', to='curriculum.unitplannermyp', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Выбор уровня изучаемого предмета',
                'verbose_name_plural': 'Выборы уровней изучаемого предмета',
                'ordering': ['unit', 'subject'],
            },
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', through='curriculum.SubjectLevelMYP', to='curriculum.Subject', verbose_name='Предметы'),
        ),
    ]
