# Generated by Django 3.2.13 on 2023-01-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0038_auto_20230120_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectdirectionrc',
            name='subject_group',
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='related_concepts',
        ),
        migrations.DeleteModel(
            name='RelatedConcept',
        ),
        migrations.DeleteModel(
            name='SubjectDirectionRC',
        ),
    ]
