# Generated by Django 3.2.13 on 2023-01-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0039_auto_20230121_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDirectionRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=128, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название на рус. языке')),
                ('subject_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdirection', to='curriculum.subjectgroupib', verbose_name='Предметная группа')),
            ],
            options={
                'verbose_name': 'Предметное направление RC',
                'verbose_name_plural': 'Предметные направления RC',
                'ordering': ['subject_group', 'name_eng'],
            },
        ),
        migrations.CreateModel(
            name='RelatedConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=64, verbose_name='Название на англ. языке')),
                ('name_rus', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название на рус. языке')),
                ('description_eng', models.TextField(blank=True, null=True, verbose_name='Описание на англ. языке')),
                ('description_rus', models.TextField(blank=True, null=True, verbose_name='Описание на рус. языке')),
                ('subdirections', models.ManyToManyField(blank=True, related_name='related_concept', to='curriculum.SubjectDirectionRC', verbose_name='Предметное направление')),
            ],
            options={
                'verbose_name': 'Сопутствующий концепт',
                'verbose_name_plural': 'Сопутствующие концепты',
                'ordering': ['subdirections__subject_group', 'name_eng'],
            },
        ),
        migrations.AddField(
            model_name='unitplannermyp',
            name='related_concepts',
            field=models.ManyToManyField(blank=True, related_name='unitplan_myp', to='curriculum.RelatedConcept', verbose_name='Сопутствующие концепты'),
        ),
    ]
