# Generated by Django 3.2.13 on 2023-01-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_auto_20230121_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryatl',
            options={'ordering': ['id'], 'verbose_name': 'ATL: Категория ', 'verbose_name_plural': 'ATL: Категории'},
        ),
        migrations.AlterModelOptions(
            name='clusteratl',
            options={'ordering': ['category', 'id'], 'verbose_name': 'ATL: Кластер', 'verbose_name_plural': 'ATL: Кластеры'},
        ),
        migrations.AlterModelOptions(
            name='explorationtodevelop',
            options={'ordering': ['gcontext', 'name_eng'], 'verbose_name': 'GC: Линия исследования', 'verbose_name_plural': 'GC: Линии исследований'},
        ),
        migrations.AlterModelOptions(
            name='globalcontext',
            options={'ordering': ['id'], 'verbose_name': 'GC: Глобальный контекст', 'verbose_name_plural': 'GC: Глобальные контексты'},
        ),
        migrations.AlterModelOptions(
            name='keyconcept',
            options={'ordering': ['name_eng'], 'verbose_name': 'KC: Ключевой концепт', 'verbose_name_plural': 'KC: Ключевые концепты'},
        ),
        migrations.AlterModelOptions(
            name='recommendsubjectkc',
            options={'ordering': ['subject_group', 'key_concept'], 'verbose_name': 'KC: Рекомендуемый предмет', 'verbose_name_plural': 'KC: Рекомендуемые предметы'},
        ),
        migrations.AlterModelOptions(
            name='relatedconcept',
            options={'ordering': ['subject_group__name_eng', 'name_eng'], 'verbose_name': 'RC: Предметный концепт', 'verbose_name_plural': 'RC: Предметные концепты'},
        ),
        migrations.AlterModelOptions(
            name='skillatl',
            options={'ordering': ['cluster', 'name_eng'], 'verbose_name': 'ATL: Навыки', 'verbose_name_plural': 'ATL: Навыки'},
        ),
        migrations.AlterModelOptions(
            name='subjectdirectionrc',
            options={'ordering': ['subject_group__name_eng', 'name_eng'], 'verbose_name': 'RC: Предметное направление', 'verbose_name_plural': 'RC: Предметные направления'},
        ),
        migrations.RemoveField(
            model_name='relatedconcept',
            name='subdirections',
        ),
        migrations.AddField(
            model_name='relatedconcept',
            name='subject_group',
            field=models.ManyToManyField(blank=True, related_name='related_concept', through='curriculum.SubjectDirectionRC', to='curriculum.SubjectGroupIB', verbose_name='Предметная группа'),
        ),
        migrations.AddField(
            model_name='subjectdirectionrc',
            name='related_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdirection', to='curriculum.relatedconcept', verbose_name='Связанный концепт'),
        ),
    ]
