# Generated by Django 3.2.13 on 2023-01-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0041_auto_20230121_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectdirectionrc',
            options={'ordering': ['name_eng'], 'verbose_name': 'RC: Предметное направление', 'verbose_name_plural': 'RC: Предметные направления'},
        ),
        migrations.RemoveField(
            model_name='subjectdirectionrc',
            name='related_concept',
        ),
        migrations.RemoveField(
            model_name='subjectdirectionrc',
            name='subject_group',
        ),
        migrations.CreateModel(
            name='ConnectSubjectRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_subjectrc', to='curriculum.relatedconcept', verbose_name='Связанный концепт')),
                ('subject_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_subjectrc', to='curriculum.subjectdirectionrc', verbose_name='Предметное направление')),
                ('subject_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_subjectrc', to='curriculum.subjectgroupib', verbose_name='Предметная группа')),
            ],
            options={
                'verbose_name': 'KC: Рекомендуемый предмет',
                'verbose_name_plural': 'KC: Рекомендуемые предметы',
                'ordering': ['subject_group', 'related_concept'],
            },
        ),
        migrations.AlterField(
            model_name='relatedconcept',
            name='subject_group',
            field=models.ManyToManyField(blank=True, related_name='related_concept', through='curriculum.ConnectSubjectRC', to='curriculum.SubjectGroupIB', verbose_name='Предметная группа'),
        ),
    ]
