# Generated by Django 3.2.13 on 2023-01-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0042_auto_20230121_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectsubjectrc',
            options={'ordering': ['subject_group', 'related_concept'], 'verbose_name': 'RC: Связь предмета и концепта', 'verbose_name_plural': 'RC: Связь предмета и концепта'},
        ),
    ]
