# Generated by Django 3.2.13 on 2023-01-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0043_alter_connectsubjectrc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedconcept',
            options={'ordering': ['id', 'subject_group__name_eng', 'name_eng'], 'verbose_name': 'RC: Предметный концепт', 'verbose_name_plural': 'RC: Предметные концепты'},
        ),
        migrations.AlterModelOptions(
            name='subjectdirectionrc',
            options={'ordering': ['id', 'name_eng'], 'verbose_name': 'RC: Предметное направление', 'verbose_name_plural': 'RC: Предметные направления'},
        ),
    ]
