# Generated by Django 3.2.13 on 2023-01-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0044_auto_20230121_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedconcept',
            options={'ordering': ['id', 'name_eng'], 'verbose_name': 'RC: Предметный концепт', 'verbose_name_plural': 'RC: Предметные концепты'},
        ),
        migrations.RemoveField(
            model_name='relatedconcept',
            name='subject_group',
        ),
        migrations.AddField(
            model_name='relatedconcept',
            name='subject_direction',
            field=models.ManyToManyField(related_name='related_concept', to='curriculum.SubjectDirectionRC', verbose_name='Предметное направление'),
        ),
        migrations.AddField(
            model_name='subjectdirectionrc',
            name='subject_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connect_subjectrc', to='curriculum.subjectgroupib', verbose_name='Предметная группа'),
        ),
        migrations.DeleteModel(
            name='ConnectSubjectRC',
        ),
    ]
