# Generated by Django 3.2.13 on 2023-01-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0045_auto_20230121_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedconcept',
            old_name='subject_direction',
            new_name='subject_directions',
        ),
    ]
