# Generated by Django 3.2.13 on 2023-01-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0046_rename_subject_direction_relatedconcept_subject_directions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='years',
        ),
        migrations.RemoveField(
            model_name='unitplannermyp',
            name='level',
        ),
    ]
