# Generated by Django 3.2.13 on 2023-01-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0047_auto_20230122_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='subject_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level', to='curriculum.subjectgroupib', verbose_name='Предметная группа'),
        ),
    ]
