# Generated by Django 3.2.13 on 2023-01-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0048_level_subject_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='subject_group',
        ),
        migrations.AddField(
            model_name='level',
            name='subject_group',
            field=models.ManyToManyField(blank=True, related_name='level', to='curriculum.SubjectGroupIB', verbose_name='Предметные группы'),
        ),
    ]
