# Generated by Django 3.2.13 on 2023-01-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0049_auto_20230122_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='subject_group',
            new_name='subject_groups',
        ),
    ]
