# Generated by Django 3.2.13 on 2023-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0050_rename_subject_group_level_subject_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atlmappingmyp',
            options={'ordering': ['planner', 'strand'], 'verbose_name': 'UnitPlan MYP: Карта навыков ATL', 'verbose_name_plural': 'UnitPlan MYP: Карты навыков ATL'},
        ),
        migrations.AlterModelOptions(
            name='inquiryquestiondp',
            options={'ordering': ['type_inq', 'question'], 'verbose_name': 'UnitPlan DP: Исследовательский вопрос', 'verbose_name_plural': 'UnitPlan DP: Исследовательские вопросы'},
        ),
        migrations.AlterModelOptions(
            name='inquiryquestionmyp',
            options={'ordering': ['type_inq', 'question'], 'verbose_name': 'UnitPlan MYP: Исследовательский вопрос', 'verbose_name_plural': 'UnitPlan MYP: Исследовательские вопросы'},
        ),
        migrations.AlterModelOptions(
            name='reflectiondp',
            options={'ordering': ['planner', 'type_post'], 'verbose_name': 'UnitPlan DP: Пост рефлексии', 'verbose_name_plural': 'UnitPlan DP: Посты рефлексии'},
        ),
        migrations.AlterModelOptions(
            name='reflectionmyp',
            options={'ordering': ['planner', 'type_post'], 'verbose_name': 'UnitPlan MYP: Пост рефлексии', 'verbose_name_plural': 'UnitPlan MYP: Посты рефлексии'},
        ),
        migrations.AlterModelOptions(
            name='subjectlevelmyp',
            options={'ordering': ['unit', 'subject'], 'verbose_name': 'UnitPlan MYP: Выбор предмета и уровня', 'verbose_name_plural': 'UnitPlan MYP: Выборы предметов и уровней'},
        ),
        migrations.AlterModelOptions(
            name='unitplannerdp',
            options={'ordering': ['class_year', 'subject', 'order', 'title'], 'verbose_name': 'UnitPlan DP: Основные данные юнита', 'verbose_name_plural': 'UnitPlan DP: Основные данные юнитов'},
        ),
        migrations.AlterModelOptions(
            name='unitplannermyp',
            options={'ordering': ['class_year', 'order', 'title'], 'verbose_name': 'UnitPlan MYP: Основные данные юнита', 'verbose_name_plural': 'UnitPlan MYP: Основные данные юнитов'},
        ),
        migrations.AlterModelOptions(
            name='unitplannermypid',
            options={'ordering': ['unitplan_myp'], 'verbose_name': 'UnitPlan MYP: Междисциплинарность', 'verbose_name_plural': 'UnitPlan MYP: Междисциплинарности'},
        ),
        migrations.AddField(
            model_name='unitplannermypid',
            name='interdisciplinary_links',
            field=models.TextField(blank=True, null=True, verbose_name='Междисциплинарные связи'),
        ),
    ]
