# Generated by Django 3.2.13 on 2023-01-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0051_auto_20230127_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitplannermypid',
            old_name='aims',
            new_name='inter_aims',
        ),
        migrations.RenameField(
            model_name='unitplannermypid',
            old_name='criteria',
            new_name='inter_criteria',
        ),
        migrations.RenameField(
            model_name='unitplannermypid',
            old_name='strands',
            new_name='inter_strands',
        ),
    ]
