# Generated by Django 3.2.18 on 2023-06-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(blank=True, max_length=1, null=True, verbose_name='Литера класса')),
                ('id_dnevnik', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID системы Дневник.РУ')),
            ],
            options={
                'verbose_name': 'Учебный класс',
                'verbose_name_plural': 'Учебные классы',
                'ordering': ['class_year', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('level', models.CharField(choices=[('1', '1 уровень'), ('2', '2 уровень'), ('3', '3 уровень'), ('0', 'Без уровня')], default='0', max_length=16, verbose_name='Уровень мероприятий')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Описание результатов')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Участие в мероприятиях',
                'verbose_name_plural': 'Участия в мероприятиях',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание типа')),
            ],
            options={
                'verbose_name': 'Тип мероприятий',
                'verbose_name_plural': 'Типы мероприятий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PeriodAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_a', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию A')),
                ('criterion_b', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию B')),
                ('criterion_c', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию C')),
                ('criterion_d', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию D')),
                ('summ_grade', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка за итоговые работы')),
                ('form_grade', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True, verbose_name='Оценка за текущие работы')),
                ('final_grade', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка')),
            ],
            options={
                'verbose_name': 'Итоговые оценки за период',
                'verbose_name_plural': 'Итоговые оценки за период',
                'ordering': ['period', 'student'],
            },
        ),
        migrations.CreateModel(
            name='ReportAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Репорты: уровнень достижений',
                'verbose_name_plural': 'Репорты: уровни достижений',
                'ordering': ['objective'],
            },
        ),
        migrations.CreateModel(
            name='ReportCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(default=None, null=True, verbose_name='Балл по критерию')),
            ],
            options={
                'verbose_name': 'Репорты: баллы за критерии',
                'verbose_name_plural': 'Репорты: баллы за критерии',
                'ordering': ['report_teacher__student', 'criterion'],
            },
        ),
        migrations.CreateModel(
            name='ReportMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время редактирования')),
            ],
            options={
                'verbose_name': 'Репорт наставника',
                'verbose_name_plural': 'Репорты наставника',
                'ordering': ['period', 'student'],
            },
        ),
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер периода')),
                ('name', models.CharField(default=None, max_length=255, null=True, verbose_name='Название периода')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Период репортов',
                'verbose_name_plural': 'Периоды репортов',
                'ordering': ['study_year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ReportPsychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время редактирования')),
            ],
            options={
                'verbose_name': 'Репорт психолога',
                'verbose_name_plural': 'Репорты психолога',
                'ordering': ['period', 'student'],
            },
        ),
        migrations.CreateModel(
            name='ReportTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст репорта')),
                ('criterion_a', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию A')),
                ('criterion_b', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию B')),
                ('criterion_c', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию C')),
                ('criterion_d', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Оценка по критерию D')),
                ('final_grade', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка по шкале 1-5')),
                ('final_grade_ib', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Итоговая оценка по шкале 1-7')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время редактирования')),
            ],
            options={
                'verbose_name': 'Репорт учителя',
                'verbose_name_plural': 'Репорты учителя',
                'ordering': ['period', 'subject__name_rus', 'author'],
            },
        ),
        migrations.CreateModel(
            name='StudyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер периода')),
                ('type', models.CharField(choices=[('trimester', 'триместр'), ('halfyear', 'полугодие')], max_length=16, verbose_name='Тип периода')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('id_dnevnik', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID системы Дневник.РУ')),
            ],
            options={
                'verbose_name': 'Учебный период',
                'verbose_name_plural': 'Учебные периоды',
                'ordering': ['study_year', 'type', 'number'],
            },
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Учебный год')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные года',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='SummativeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название итоговой работы')),
            ],
            options={
                'verbose_name': 'ИР: Основаная информация',
                'verbose_name_plural': 'ИР: Основная информация',
                'ordering': ['period', 'subject', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(default=0, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'ИР: Журналы',
                'verbose_name_plural': 'ИР: Журналы',
                'ordering': ['work_date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='WorkCriteriaMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(default=0, verbose_name='Оценка по критерию')),
            ],
            options={
                'verbose_name': 'ИР: Оценки по критериям',
                'verbose_name_plural': 'ИР: Оценки по критериям',
                'ordering': ['work_assess', 'criterion'],
            },
        ),
        migrations.CreateModel(
            name='WorkGroupDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('lesson', models.PositiveSmallIntegerField(default=1, verbose_name='Номер урока')),
            ],
            options={
                'verbose_name': 'ИР: Классы',
                'verbose_name_plural': 'ИР: Классы',
                'ordering': ['work', 'group', 'date'],
            },
        ),
        migrations.CreateModel(
            name='WorkLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Часы')),
                ('groups', models.ManyToManyField(blank=True, related_name='workload', to='assess.ClassGroup', verbose_name='Классы')),
                ('study_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='assess.studyyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Рабочая нагрузка',
                'verbose_name_plural': 'Рабочие нагрузки',
                'ordering': ['study_year', 'subject', 'groups__class_year', 'teacher'],
            },
        ),
    ]
