# Generated by Django 3.2.18 on 2023-06-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assess', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='curriculum.subject', verbose_name='Предмет'),
        ),
    ]
