# Generated by Django 3.2.18 on 2023-06-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('assess', '0002_workload_subject'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to='member.profileteacher', verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='workgroupdate',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workgroup', to='assess.classgroup', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='workgroupdate',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='workgroup', through='assess.WorkAssessment', to='member.ProfileStudent', verbose_name='Оценки студентов'),
        ),
        migrations.AddField(
            model_name='workgroupdate',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workgroup', to='assess.summativework', verbose_name='Итоговая работа'),
        ),
        migrations.AddField(
            model_name='workcriteriamark',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_criteria_mark', to='curriculum.criterion', verbose_name='Критерий оценки'),
        ),
        migrations.AddField(
            model_name='workcriteriamark',
            name='work_assess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_criteria_mark', to='assess.workassessment', verbose_name='Позиция оценки в юните'),
        ),
        migrations.AddField(
            model_name='workassessment',
            name='criteria_marks',
            field=models.ManyToManyField(blank=True, related_name='workassess', through='assess.WorkCriteriaMark', to='curriculum.Criterion'),
        ),
        migrations.AddField(
            model_name='workassessment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workassess', to='member.profilestudent', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='workassessment',
            name='work_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workassess', to='assess.workgroupdate', verbose_name='Дата итоговой работы'),
        ),
        migrations.AddField(
            model_name='summativework',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='sumwork', to='curriculum.Criterion', verbose_name='Критерии оценки'),
        ),
        migrations.AddField(
            model_name='summativework',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='sumwork', through='assess.WorkGroupDate', to='assess.ClassGroup', verbose_name='Классы'),
        ),
        migrations.AddField(
            model_name='summativework',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumwork', to='assess.studyperiod', verbose_name='Период обучения'),
        ),
        migrations.AddField(
            model_name='summativework',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumwork', to='curriculum.subject', verbose_name='Учебный предмет'),
        ),
        migrations.AddField(
            model_name='summativework',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumwork', to='member.profileteacher', verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='summativework',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sumwork', to='curriculum.unitplannermyp', verbose_name='Юнит'),
        ),
        migrations.AddField(
            model_name='studyperiod',
            name='class_year',
            field=models.ManyToManyField(blank=True, related_name='period', to='curriculum.ClassYear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='studyperiod',
            name='study_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period', to='assess.studyyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='teacher_reports', to='assess.ReportAchievements', verbose_name='Уровни достижений'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='member.profileteacher', verbose_name='Автор репорта'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='criteria',
            field=models.ManyToManyField(blank=True, related_name='teacher_reports', through='assess.ReportCriteria', to='curriculum.Criterion', verbose_name='Критерии '),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='teacher_reports', to='assess.EventParticipation', verbose_name='Участие в мероприятиях'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='assess.reportperiod', verbose_name='Период репорта'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='member.profilestudent', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='curriculum.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='reportteacher',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reports', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='reportpsychologist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_reports', to='member.profileteacher', verbose_name='Автор репорта'),
        ),
        migrations.AddField(
            model_name='reportpsychologist',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='psycho_reports', to='assess.EventParticipation', verbose_name='Участие в мероприятиях'),
        ),
        migrations.AddField(
            model_name='reportpsychologist',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_reports', to='assess.reportperiod', verbose_name='Период репорта'),
        ),
        migrations.AddField(
            model_name='reportpsychologist',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_reports', to='member.profilestudent', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='reportpsychologist',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_reports', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='reportperiod',
            name='assessment_periods',
            field=models.ManyToManyField(blank=True, related_name='report_period', to='assess.StudyPeriod', verbose_name='Оценочные периоды'),
        ),
        migrations.AddField(
            model_name='reportperiod',
            name='study_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_period', to='assess.studyyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='reportmentor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reports', to='member.profileteacher', verbose_name='Автор репорта'),
        ),
        migrations.AddField(
            model_name='reportmentor',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='mentor_reports', to='assess.EventParticipation', verbose_name='Участие в мероприятиях'),
        ),
        migrations.AddField(
            model_name='reportmentor',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reports', to='assess.reportperiod', verbose_name='Период репорта'),
        ),
        migrations.AddField(
            model_name='reportmentor',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reports', to='member.profilestudent', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='reportmentor',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_reports', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='reportcriteria',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_criteria', to='curriculum.criterion', verbose_name='Критерий оценки'),
        ),
        migrations.AddField(
            model_name='reportcriteria',
            name='report_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_criteria', to='assess.reportteacher', verbose_name='Репорт учителя'),
        ),
        migrations.AddField(
            model_name='reportachievements',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_achievements', to='curriculum.achievementlevel', verbose_name='Уровень достижений'),
        ),
        migrations.AddField(
            model_name='reportachievements',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_achievements', to='curriculum.objective', verbose_name='Предметная цель'),
        ),
        migrations.AddField(
            model_name='periodassessment',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodassess', to='assess.studyperiod', verbose_name='Период'),
        ),
        migrations.AddField(
            model_name='periodassessment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodassess', to='member.profilestudent', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='periodassessment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodassess', to='curriculum.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='periodassessment',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodassess', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assess.eventtype', verbose_name='Тип мероприятия'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='class_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='curriculum.classyear', verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='member.profileteacher', verbose_name='Наставник'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psycho_groups', to='member.profileteacher', verbose_name='Психолог'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='member.ProfileStudent', verbose_name='Студенты'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='study_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='assess.studyyear', verbose_name='Учебный год'),
        ),
    ]
