# Generated by Django 3.2.18 on 2023-06-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportteacher',
            name='criterion_a',
        ),
        migrations.RemoveField(
            model_name='reportteacher',
            name='criterion_b',
        ),
        migrations.RemoveField(
            model_name='reportteacher',
            name='criterion_c',
        ),
        migrations.RemoveField(
            model_name='reportteacher',
            name='criterion_d',
        ),
    ]
